-- Module      : Verismith.Verilog2005
-- Description : Verilog 2005 compliant implementation with context free random generation.
-- Copyright   : (c) 2023, Quentin Corradi
-- License     : GPL-3
-- Maintainer  : q [dot] corradi22 [at] imperial [dot] ac [dot] uk
-- Stability   : experimental
-- Portability : POSIX

module Verismith.Verilog2005
  ( parseVerilog2005,
    genSource,
    runGarbageGeneration,
    GeneratorOpts,
    GenM,
    NumberProbability,
    CategoricalProbability,
    defGeneratorOpts,
    GenMinTypMax (..),
    MinTypMax,
    CMinTypMax,
    Identified (..),
    defaultIdM,
    UnaryOperator (..),
    BinaryOperator (..),
    Number (..),
    GenPrim (..),
    HierIdent (..),
    GenDimRange (..),
    DimRange (..),
    CDimRange (..),
    GenExpr (..),
    Expr (..),
    CExpr (..),
    Attribute (..),
    Attributed (..),
    AttrIded (..),
    Dir (..),
    Range2 (..),
    GenRangeExpr (..),
    RangeExpr,
    CRangeExpr,
    NumIdent (..),
    Delay3 (..),
    Delay2 (..),
    Delay1 (..),
    SignRange (..),
    EventPrefix (..),
    SpecTerm (..),
    ComType (..),
    FunParType (..),
    NetType (..),
    Strength (..),
    DriveStrength (..),
    dsDefault,
    ChargeStrength (..),
    LValue (..),
    NetLValue,
    VarLValue,
    NetAssign (..),
    VarAssign (..),
    ParamAssign (..),
    PortAssign (..),
    EventPrim (..),
    EventControl (..),
    DelayEventControl (..),
    ProcContAssign (..),
    LoopStatement (..),
    CaseItem (..),
    Statement (..),
    AttrStmt,
    MybStmt,
    NInputType (..),
    GateInst (..),
    EdgeDesc (..),
    TimingCheckEvent (..),
    ControlledTimingCheckEvent (..),
    STCArgs (..),
    STCAddArgs (..),
    SystemTimingCheck (..),
    ModulePathCondition (..),
    SpecPath (..),
    SpecifyItem (..),
    ParamOver (..),
    SpecParamDecl (..),
    SpecParam (..),
    NetKind (..),
    BlockDecl (..),
    StdBlockDecl,
    TaskFunType (..),
    ModGenDecl (..),
    GenCaseItem (..),
    ModGenItem (..),
    ModuleItem (..),
    Parameter (..),
    PortDecl (..),
    GenerateRegion (..),
    GenerateItem (..),
    GenerateBlock (..),
    ModuleBlock (..),
    SigLevel (..),
    ZOX (..),
    CombRow (..),
    Edge (..),
    SeqIn (..),
    SeqRow (..),
    PrimTable (..),
    PrimitiveBlock (..),
    Dot1Ident (..),
    LLU (..),
    ConfigItem (..),
    ConfigBlock (..),
    Verilog2005 (..),
    SourceInfo (..),
    SystemFunction (..),
    Logic (..),
    BXZ (..),
    OXZ (..),
    HXZ (..),
  )
where

import Verismith.Verilog2005.AST
import Verismith.Verilog2005.Generator
import Verismith.Verilog2005.Parser
import Verismith.Verilog2005.PrettyPrinter
import Verismith.Verilog2005.Randomness
