#!/usr/bin/env python3

import subprocess

def main():
        i = 0
        name = "output_vivado_all"
        config = "experiments/vivado_all.toml"
        iterations = 50
        while True:
                subprocess.call(["verifuzz", "fuzz", "-o", name + str(i), "-c", config, "-n", str(iterations)])
                i += 1

if __name__ == '__main__':
        main()
